import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SusuNavBar from './components/SusuNavBar/SusuNavBar'
import SusuFooter from './components/SusuFooter/SusuFooter'
import { AuthProvider } from './contexts/AuthContext'
import { RedirectContextProvider } from './contexts/RedirectContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <RedirectContextProvider>
          <SusuNavBar />
            {children}
          </RedirectContextProvider>
        </AuthProvider>
      <SusuFooter />
        </body>
    </html>
  )
}
