import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SusuNavBar from './components/SusuNavBar/SusuNavBar'
import SusuFooter from './components/SusuFooter/SusuFooter'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <SusuNavBar />
        {children}
      <SusuFooter />
        </body>
    </html>
  )
}
